#!/usr/bin/env ksh

#-------------------------------------------------------------------------------
#         Copyright (C) 2023    Steve Price    SuperStevePrice@gmail.com
#
#                       GNU GENERAL PUBLIC LICENSE
#                        Version 3, 29 June 2007
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# PROGRAM:
#	~/.aliases
#	
# PURPOSE:
#	Defines some aliases
#	
# USAGE:
#	Invoked by ~/.profile at login.
#
#-------------------------------------------------------------------------------
alias c="tput clear"		    # clear the screen
alias print="echo"			    # bash has no print
alias clr="tput clear"		    # clear the screen
alias h="fc -l"				    # history command for ksh
alias l="ls -l"				    # short for long list ls
alias ll="ls -l"			    # short for long list ls
alias lr="ls -ltr"			    # short for long list time reversed ls
alias g="$(which git)"		    # short for git
alias gl="$(which git) log"	    # short for git log
alias gs="$(which git) status"	# short for git status
alias vl="view logs/setup.log"	# to view project setup log
alias get=g  				    # avoid common typo
alias gits="g status"		    # shorthand for 'git status'

# perltidy requires special handling:
pt_path="/opt/homebrew/Cellar/perl/5.36.1/bin"
alias perltidy="${pt_path}/perltidy -pro=~/.perltidyrc"

if [ "$(uname)" == "Darwin" ]; then
    alias python=/Users/steve/anaconda3/bin/python3.10
else
    alias python="$(which python3)"
fi
alias py=python
