#!/usr/bin/env ksh

#-------------------------------------------------------------------------------
# Copyright (C) 2023 Steve Price SuperStevePrice@gmail.com
#
# GNU GENERAL PUBLIC LICENSE
# Version 3, 29 June 2007
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# PROGRAM:
#   .profile  
#   
# PURPOSE:
#   ksh profile
#   
# USAGE:
#   Invoked by the operating system at login.
#-------------------------------------------------------------------------------

# PS1: command line primary prompt:
. ~/bin/PS1.ksh

# load my aliases
. ~/.aliases

# load my functions
. ~/.functions

export HOST=$(uname -n)
export FCEDIT=vi

# Set the standard locations for common utilities
PATH="/bin:/usr/bin:/usr/local/bin:/usr/sbin:/sbin"

# Add additional directories if needed
PATH="$PATH:/opt/X11/bin:/opt/homebrew/bin"
PATH="$PATH:$HOME/bin:$HOME/anaconda3/bin:."

# Remove duplicates from PATH
export PATH=$(echo $PATH | awk -v RS=':' '!a[$0]++ {if (NR>1) printf(":"); printf("%s", $0)}')

# Detect the operating system and set environment to run perl Tk modules.
if [ "$(uname)" == "Darwin" ]; then
    # macOS specific configurations. Not required for Linux.
    eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"

    # If brew is installed, set the environment:
    brew=$(command -v brew)
    if [ -n "$brew" ]; then
        eval "$("$brew" shellenv)"
    fi
    PYTHONPATH="/Users/steve/anaconda3/lib/python3.10"
    PYTHONPATH="${PYTHONPATH}/site-packages/tkmacosx:$PYTHONPATH"
    export PYTHONPATH
fi

# Remove duplicates from PYTHONPATH
export PYTHONPATH=$(echo $PYTHONPATH | awk -v RS=':' '!a[$0]++ {if (NR>1) printf(":"); printf("%s", $0)}')


# Setting the terminal type for xterm and Terminal windows. 
export TERM=xterm-256color

# Python Tk Warning:
# DEPRECATION WARNING: The system version of Tk is deprecated and may be 
# removed in a future release. Please don't rely on it. 
# Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
export TK_SILENCE_DEPRECATION=1

# Conda initialization for ksh:
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup=$('/home/steve/anaconda3/bin/conda' 'shell.ksh' 'hook' 2> /dev/null)
if [ $? -eq 0 ]; then
        eval "$__conda_setup"
    else
        if [ -f "/home/steve/anaconda3/etc/profile.d/conda.sh" ]; then
            . "/home/steve/anaconda3/etc/profile.d/conda.sh"
        else
            export PATH="/home/steve/anaconda3/bin:$PATH"
        fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Enable CLI editing of previous commands in history:
set -o vi
